Repository ratifire/devrate-web, pull requests merged in 2024-10, with the labels that each got.

#744 Add filtred #726
  src/components/FormsComponents/Inputs/TextAreaSearch/TextAreaSearch.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Achievement/Achievment.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Education/Education.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/ExperienceSection.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/Skills.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/Skills.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsItem/SkillsItem.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsItem/SkillsItem.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsList/SkillsList.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsList/SkillsList.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/WorkExperience/WorkExperience.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/WorkExperience/WorkExperience.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Achievement/Achievement.style.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Education/Education.style.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/ExperienceSection.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/Skills.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/Skills.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/SkillsItem/SkillsItem.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/SkillsItem/SkillsItem.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/updateAllSpecialization.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/WorkExperience/WorkExperience.styles.js
  src/components/UI/CustomTooltip/CustomTooltip.jsx
  src/pages/ProfilePages/PersonalProfilePage/PersonalProfilePage.styles.js
  src/pages/ProfilePages/UserProfilePage/UserProfilePage.styles.js
  src/redux/user/personal/personalApiSlice.js
  src/utils/helpers/sortedSkills.js
  src/utils/helpers/sortedSkillsByOriginal.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/theme/theme.js
Labels: Tech. Debt

#746 Added some changes to profile pages
  src/assets/icons/ProfileRightSection/behance.svg
  src/assets/icons/ProfileRightSection/github.svg
  src/assets/icons/ProfileRightSection/linkedin.svg
  src/assets/icons/ProfileRightSection/mail.svg
  src/assets/icons/ProfileRightSection/phone.svg
  src/assets/icons/ProfileRightSection/telegram.svg
  src/assets/icons/behance-filled.svg
  src/assets/icons/github-filled.svg
  src/assets/icons/linkedin-filled.svg
  src/assets/icons/mail-filled.svg
  src/assets/icons/phone-filled.svg
  src/assets/icons/telegram-filled.svg
  src/components/PageComponents/ProfileComponents/PersonalProfile/BaseUserInfo/BaseUserInfo.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/RightSection/RightSection.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/RightSection/RightSection.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/BaseUserInfo/BaseUserInfo.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/BaseUserInfo/BaseUserInfo.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/RightSection/RightSection.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/RightSection/RightSection.style.js
  src/components/PageComponents/ProfileComponents/sharedComponents/EmptyExperienceTab/EmptyExperienceTab.jsx
  src/components/PageComponents/ProfileComponents/sharedComponents/EmptyExperienceTab/EmptyExperienceTab.style.js
  src/components/UI/LinearProgressWithLabel/LinearProgressWithLabel.jsx
  src/components/UI/LinearProgressWithLabel/LinearProgressWithLabel.styles.js
  src/components/UI/UserAvatar/UserAvatar.jsx
  src/components/UI/UserAvatar/UserAvatar.styles.js
  src/utils/constants/emptyTabsPictures.js
  src/utils/constants/userSocials.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: Tech. Debt

#749 748 fix
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/ScheduleInterviewModal.jsx
  src/components/ModalsComponents/SpecializationModals/SpecializationModal/SpecializationModal.jsx
  src/pages/SpecializationPage/SpecialisationPage.jsx
  src/utils/theme/theme.js
Labels: bug

#759 refactor_prophile_hard_skills
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/Skills.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsItem/SkillsItem.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsItem/SkillsItem.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsList/SkillsList.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsList/SkillsList.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/Skills.jsx
  src/redux/specialization/specializationApiSlice.js
  src/redux/user/personal/personalApiSlice.js
Labels: Tech. Debt

#770 Fixed the problem with DropDown menu in WorkExperience tab
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/WorkExperience/WorkExperienceItem/WorkExperienceItem.jsx
Labels: bug

#805 added little changes.
  .storybook/preview.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsList/SkillsList.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/Skills.styles.js
  src/components/PageComponents/ProfileComponents/sharedComponents/EmptyExperienceTab/EmptyExperienceTab.jsx
  src/components/PageComponents/ProfileHeader/InputSearch/ModalSearch/ModalSearch.jsx
  src/components/PageComponents/ScheduleComponents/Sidebar/SmallCalendar/DayPicker/DayPicker.jsx
  src/components/UI/SocialsLinkList/SocialsLinkList.jsx
  src/components/UI/ThemeSwitch/ThemeSwitch.jsx
  src/redux/theme/themeSlice.js
  src/utils/constants/Theme/theme.js
  src/utils/constants/Theme/themeIcons.js
  src/utils/theme/theme.js
Labels: Tech. Debt

#826 Fix bug with error messsage in WE modal
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.jsx
  src/utils/valadationSchemas/WorkExperienceModalSchema.js
Labels: bug, DevBug

#821 User names in calendar modal #808
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.styles.js
  src/pages/ShedulePage/SchedulePage.styles.js
Labels: Tech. Debt

#847 846 bug fix
  src/components/ModalsComponents/SpecializationModals/HardSkillsModal/HardSkillsModal.jsx
  src/components/ModalsComponents/SpecializationModals/HardSkillsModal/HardSkillsModal.styles.js
  src/components/ModalsComponents/SpecializationModals/SoftSkillsModal/SoftSkillsModal.jsx
  src/components/PageComponents/ProfileHeader/InputSearch/InputSearch.jsx
  src/utils/hooks/useMergeState.js
Labels: bug, DevBug

#844 831 bug fix
  src/redux/specialization/specializationApiSlice.js
Labels: bug

#835 update stepLanguage
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepLanguage/StepLanguage.jsx
Labels: bug

#828 update reset password form
  src/utils/constants/regularExpressions.js
  src/utils/valadationSchemas/RegistrationSchema.js
  src/utils/valadationSchemas/ResetPasswordSchema.js
Labels: bug

#852 DW-619/change-password-requirements
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: bug

#854 change-error-message
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/ResetPassword/ResetPassword.jsx
  src/redux/store/store.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: bug

#851 817 feature
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/CheckboxButton/CheckboxButton.jsx
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/CheckboxButton/CheckboxButton.styles.js
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/ScheduleInterview.styles.js
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/ScheduleInterviewModal.jsx
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/ScheduleInterviewModal.styles.js
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/components/RenderTimeSlots.jsx
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/components/TabsRender.jsx
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/components/WeekNavigation.jsx
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/components/styles.js
  src/components/PageComponents/SpecializationComponents/Interviews/Interviews.jsx
  src/components/PageComponents/SpecializationComponents/Interviews/Interviews.styles.js
  src/redux/specialization/specializationApiSlice.js
  src/utils/helpers/getUserUTC.js
  src/utils/helpers/index.js
  src/utils/theme/theme.js
Labels: enhancement

#853 fix: error in svg
  src/components/PageComponents/SpecializationComponents/Statistics/HardSkillsChart/HardSkillsChart.jsx
Labels: bug

#858 fix: modalFeedbackInterview theme
  src/utils/theme/theme.js
Labels: bug

#855 fix: loading event in current week
  src/components/PageComponents/ScheduleComponents/Schedule.jsx
Labels: bug

#859 Fixed bug with text and icon color when all data is complete on the p…
  src/components/UI/LinearProgressWithLabel/LinearProgressWithLabel.styles.js
  src/utils/theme/theme.js
Labels: bug

#860 Added color and hover color on links in calendar modal.
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.styles.js
  src/utils/theme/theme.js
Labels: enhancement

#864 Work Experience: Fix missing 'Currently at this position'
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.jsx
  src/utils/helpers/generateYearsArray.js
Labels: bug

#872 fix: save personal information regardless of "City" field changes
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepPersonal/StepPersonal.jsx
  src/utils/valadationSchemas/RegistrationSchema.js
  src/utils/valadationSchemas/StepPersonalSchema.js
Labels: bug
