Repository ratifire/devrate-web, pull requests merged in 2024-12, with the labels that each got.

#996 991 bug fix
  src/components/PageComponents/SpecializationComponents/SpecializationCategories/SpecializationCategories.jsx
  src/pages/SpecializationPage/SpecialisationPage.styles.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: bug, DevBug

#1005 fix prod
  .husky/install.mjs
  package.json
Labels: bug, DevBug

#1016 Dw 1012/migration to react router V7
  README.md
  package-lock.json
  package.json
  src/App.jsx
  src/components/ModalsComponents/AuthModals/LoginModal/LoginModal.jsx
  src/components/ModalsComponents/AuthModals/RegistrationModal/RegistrationModal.jsx
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/CheckEmail/CheckEmail.jsx
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/ResetPassword/ResetPassword.jsx
  src/components/PageComponents/LandingComponents/Footer/Footer.jsx
  src/components/PageComponents/LandingComponents/Footer/Footer.stories.js
  src/components/PageComponents/LandingComponents/Header/Header.jsx
  src/components/PageComponents/LandingComponents/Header/Header.stories.js
  src/components/PageComponents/Menu/Menu.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/ExperienceSection.stories.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/RightSection/RightSection.stories.js
  src/components/PageComponents/ProfileComponents/sharedComponents/EmptyExperienceTab/EmptyExperienceTab.jsx
  src/components/PageComponents/ProfileHeader/InputSearch/ModalSearch/ModalSearch.jsx
  src/components/PageComponents/ProfileHeader/ProfileHeader.jsx
  src/components/PageComponents/ProfileHeader/ProfileHeader.stories.js
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
  src/components/PageComponents/ScheduleComponents/SidebarEvent/SidebarEvent.jsx
  src/components/UI/LinkList/LinkList.jsx
  src/components/UI/LinkList/LinkList.stories.js
  src/components/UI/SocialsLinkList/SocialsLinkList.stories.js
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/HomePage/sections/Header/Header.jsx
  src/pages/HomePage/sections/HeroSection/HeroSection.jsx
  src/pages/ProfilePages/UserProfilePage/UserProfilePage.jsx
  src/redux/auth/RequireAuth.js
  src/redux/services/api/apiSlice.js
  src/router/UserProfileRoute.js
  src/router/router.js
Labels: Tech. Debt

#1019 migrate MUIv5 on MUIv6
  package-lock.json
  package.json
Labels: Tech. Debt

#1017 add text and fix notification
  src/components/PageComponents/Notification/NotificationItem/NotificationItem.jsx
  src/components/PageComponents/Notification/NotificationsType/InterviewFeedback.jsx
  src/components/PageComponents/Notification/NotificationsType/InterviewRejected.jsx
  src/components/PageComponents/Notification/NotificationsType/InterviewRequestExpired.jsx
  src/components/PageComponents/Notification/NotificationsType/InterviewScheduled.jsx
  src/utils/helpers/formatToLocalDate.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/theme/theme.js
Labels: Tech. Debt

#1011 #990 refactoring the event deletion function
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
  src/components/PageComponents/ScheduleComponents/SidebarEvent/SidebarEvent.jsx
  src/utils/hooks/useDeleteEvent.js
Labels: enhancement

#1024 Feature/#987 buttons update
  package-lock.json
  package.json
  src/components/FormsComponents/Buttons/ButtonDef/ButtonDef.jsx
  src/components/FormsComponents/Buttons/ButtonDef/ButtonDef.styles.js
  src/components/FormsComponents/Inputs/SelectLanguage/SelectLanguage.jsx
  src/components/ModalsComponents/AuthModals/ConfirmationModal/ConfirmationForm.jsx
  src/components/ModalsComponents/AuthModals/ConfirmationModal/ConfirmationModal.jsx
  src/components/ModalsComponents/AuthModals/ConfirmationModal/ConfirmationModal.styles.js
  src/components/ModalsComponents/AuthModals/LoginModal/LoginModal.jsx
  src/components/ModalsComponents/AuthModals/RegistrationModal/RegistrationModal.jsx
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/CheckEmail/CheckEmail.jsx
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/NotificationModal/NotificationModal.jsx
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/ResetPassword/ResetPassword.jsx
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/components/CandidateFeedback/CandidateFeedback.jsx
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/components/InterviewerFeedback/InterviewerFeedback.jsx
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/hooks/useFeedbackForm.js
  src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
  src/components/ModalsComponents/ProfileModals/AchievementModal/AchievementEditModal.jsx
  src/components/ModalsComponents/ProfileModals/AchievementModal/AchievementModal.jsx
  src/components/ModalsComponents/ProfileModals/EducationModal/EducationModal.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/StepContacts.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepLanguage/StepLanguage.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepPersonal/StepPersonal.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepPersonal/StepPersonal.styles.js
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.jsx
  src/components/ModalsComponents/SpecializationModals/HardSkillsModal/HardSkillsModal.jsx
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/ScheduleInterviewModal.jsx
  src/components/ModalsComponents/SpecializationModals/SoftSkillsModal/SoftSkillsModal.jsx
  src/components/ModalsComponents/SpecializationModals/SpecializationModal/SpecializationModal.jsx
  src/components/PageComponents/LandingComponents/Header/Header.jsx
  src/components/PageComponents/LandingComponents/HeroSection/HeroSection.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/BaseUserInfo/BaseUserInfo.jsx
  src/components/PageComponents/ProfileComponents/sharedComponents/EmptyExperienceTab/EmptyExperienceTab.jsx
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
  src/components/PageComponents/SpecializationComponents/SpecializationCategories/SpecializationCategories.jsx
  src/components/PageComponents/SpecializationComponents/SpecializationLevel/SpecializationLevel.jsx
  src/components/UI/LoadImages/LoadImages.jsx
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepAvatarSkeleton/StepAvatarSkeleton.jsx
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepContactsSkeleton/StepContactsSkeleton.jsx
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepLanguageSkeleton/StepLanguageSkeleton.jsx
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepPersonalSkeleton/StepPersonalSkeleton.jsx
  src/redux/modal/modalSlice.js
  src/utils/theme/theme.js
Labels: enhancement

#1041 fix: bugs layout
  src/components/FormsComponents/Inputs/FormInput/FormInput.styles.js
  src/components/FormsComponents/Inputs/TextAreaInput/TextAreaInput.styles.js
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.jsx
Labels: bug, DevBug

#1042 1037 husky doc
  .eslintignore
  docs/husky/HUSKY.md
  docs/husky/screenshots/eslint-ignore.png
  docs/husky/screenshots/package-json-lint-staged.png
  docs/husky/screenshots/package-json-script.png
  docs/husky/screenshots/pre-commit.png
  docs/husky/screenshots/prettier-ignore.png
Labels: documentation

#1048 1020
  src/assets/icons/send.svg
  src/components/PageComponents/Chat/Chat.jsx
  src/components/PageComponents/Chat/Chat.styles.js
  src/components/PageComponents/Chat/ChatForm/CharFrom.styles.js
  src/components/PageComponents/Chat/ChatForm/ChatForm.jsx
  src/components/PageComponents/Chat/ChatForm/ChatMessage/ChatMessage.jsx
  src/components/PageComponents/Chat/ChatForm/ChatMessage/ChatMessage.styles.js
  src/components/PageComponents/Chat/ChatForm/ChatMessage/index.js
  src/components/PageComponents/Chat/ChatForm/index.js
  src/components/PageComponents/Chat/index.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/BaseUserInfo/BaseUserInfo.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/BaseUserInfo/BaseUserInfo.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/BaseUserInfo/BaseUserInfo.styles.js
  src/components/PageComponents/ProfileHeader/ProfileHeader.jsx
  src/components/UI/UserAvatar/UserAvatar.jsx
  src/components/UI/UserAvatar/UserAvatar.styles.js
  src/redux/chat/chatSlice.js
  src/redux/store/store.js
  src/utils/constants/testMessages.js
Labels: Tech. Debt

#1057 Faq2.0 #974
  package-lock.json
  src/pages/HomePage/sections/FAQSection/Faq.module.scss
  src/pages/HomePage/sections/FAQSection/ItemFaq/ItemFaq.jsx
  src/pages/HomePage/sections/FAQSection/ItemFaq/ItemFaq.module.scss
  src/pages/HomePage/sections/Footer/footer.module.scss
  src/pages/HomePage/sections/HowItWorksSection/HowItWorksSection.module.scss
Labels: DevBug
