Repository ratifire/devrate-web, pull requests merged in 2024-11, with the labels that each got.

#871 update confirmation form
  src/components/ModalsComponents/AuthModals/ConfirmationModal/ConfirmationForm.jsx
Labels: bug

#870 Dw 790/mask user mail
  src/components/ModalsComponents/AuthModals/ConfirmationModal/ConfirmationModal.jsx
  src/components/ModalsComponents/AuthModals/RegistrationModal/RegistrationModal.jsx
Labels: bug

#877 769 bug fix
  .github/workflows/node.js.yml
  src/components/ModalsComponents/SpecializationModals/SpecializationModal/SpecializationModal.jsx
  src/components/PageComponents/SpecializationComponents/SpecializationCategories/SpecializationCategories.jsx
  src/redux/store/store.js
  src/utils/constants/Specialization/modalSpecialization.js
Labels: bug, DevBug

#876 fix: regEx
  src/components/PageComponents/ProfileHeader/InputSearch/helpers/formatSearchQuery.js
Labels: bug, DevBug

#892 873 bug fix
  src/components/FormsComponents/Inputs/AdvanceFormSelector/AdvancedFormSelector.jsx
  src/components/FormsComponents/Inputs/AdvanceFormSelector/AdvancedFormSelector.styles.js
  src/components/ModalsComponents/SpecializationModals/SpecializationModal/SpecializationModal.styles.js
  src/components/PageComponents/SpecializationComponents/SpecializationLevel/SpecializationLevel.styles.js
  src/components/UI/LinearProgressWithLabel/LinearProgressWithLabel.styles.js
  src/utils/theme/specialization/specializationDark.js
  src/utils/theme/specialization/specializationLight.js
Labels: bug, DevBug

#893 refactor cookie removing
  src/components/PageComponents/Menu/Menu.jsx
Labels: bug

#894 Dw 881/update calendar sidebar
  src/components/PageComponents/ScheduleComponents/Sidebar/Sidebar.styles.js
Labels: DevBug

#897 fix: locales
  src/utils/locales/en/index.js
Labels: bug, DevBug

#896 fix: border color
  src/components/UI/Specialization/SpecializationSkills/SpecializationSkills.styles.js
  src/utils/theme/specialization/specializationLight.js
Labels: bug

#885 Edited menu
  src/components/ModalsComponents/FeedbackProjectModal/FeedbackProjectModal.jsx
  src/components/PageComponents/Menu/Menu.jsx
  src/components/PageComponents/Menu/Menu.styles.js
  src/utils/locales/en/index.js
Labels: enhancement

#904 fix: space in email field
  src/components/FormsComponents/Inputs/FormInput/FormInput.jsx
  src/components/ModalsComponents/AuthModals/RegistrationModal/RegistrationModal.jsx
Labels: bug

#908 807 bug fix
  src/components/PageComponents/Menu/Menu.jsx
  src/components/PageComponents/Menu/Menu.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/SkillsSection/SkillsSection.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/SkillsSection/SkillsSection.styles.js
  src/components/PageComponents/ProfileHeader/ProfileHeader.styles.js
  src/components/PageComponents/ScheduleComponents/CustomScrollContainer/CustomScrollContainer.tsx
  src/components/PageComponents/ScheduleComponents/Schedule.jsx
  src/components/PageComponents/ScheduleComponents/Schedule.styles.js
  src/components/PageComponents/SpecializationComponents/SpecializationLevel/SpecializationLevel.styles.js
  src/components/UI/Specialization/SpecializationSkills/SpecializationSkills.styles.js
  src/pages/ProfilePages/PersonalProfilePage/PersonalProfilePage.styles.js
  src/pages/ProfilePages/UserProfilePage/UserProfilePage.styles.js
  src/pages/ShedulePage/SchedulePage.styles.js
  src/pages/SpecializationPage/SpecialisationPage.styles.js
  src/utils/theme/schedule/index.js
  src/utils/theme/schedule/scheduleDark.js
  src/utils/theme/schedule/scheduleLight.js
  src/utils/theme/specialization/specializationLight.js
  src/utils/theme/theme.js
Labels: bug, DevBug

#910 883 bug fix
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/Skills.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/updateAllSpecialization.js
Labels: bug, DevBug

#902 refactor event popup
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
  src/components/PageComponents/ScheduleComponents/Schedule.jsx
Labels: DevBug

#900 update styles of loadImages
  src/components/UI/LoadImages/LoadImages.styles.js
Labels: bug

#923 913 faq skeleton
  src/components/PageComponents/FaqComponents/Blog/Blog.jsx
  src/components/PageComponents/FaqComponents/Blog/blogArr.js
  src/components/UI/Skeleton/Pages/faqSkeleton/BlogSkeleton/BlogSkeleton.jsx
  src/components/UI/Skeleton/Pages/faqSkeleton/BlogSkeleton/BlogSkeleton.styles.js
  src/components/UI/Skeleton/Pages/faqSkeleton/BlogSkeleton/index.js
  src/components/UI/Skeleton/Pages/faqSkeleton/FaqSkeleton/FaqSkeleton.jsx
  src/components/UI/Skeleton/Pages/faqSkeleton/FaqSkeleton/FaqSkeleton.styles.js
  src/components/UI/Skeleton/Pages/faqSkeleton/FaqSkeleton/index.js
  src/components/UI/Skeleton/Pages/faqSkeleton/index.js
  src/components/UI/Skeleton/index.js
  src/pages/FaqPage/FaqPage.jsx
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: enhancement

#921 fix: state in WorkExperienceModal.jsx
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.jsx
Labels: bug, DevBug

#931 930 skeleton
  src/components/PageComponents/ScheduleComponents/Schedule.jsx
  src/components/UI/Skeleton/Pages/ScheduleSkeleton/ScheduleSkeleton.jsx
  src/components/UI/Skeleton/Pages/ScheduleSkeleton/ScheduleSkeleton.styles.js
  src/components/UI/Skeleton/Pages/ScheduleSkeleton/components/FullCalendarSkeleton/FullCalendarSkeleton.jsx
  src/components/UI/Skeleton/Pages/ScheduleSkeleton/components/FullCalendarSkeleton/FullCalendarSkeleton.styles.js
  src/components/UI/Skeleton/Pages/ScheduleSkeleton/components/FullCalendarSkeleton/index.js
  src/components/UI/Skeleton/Pages/ScheduleSkeleton/components/SidebarSkeleton/SidebarSkeleton.jsx
  src/components/UI/Skeleton/Pages/ScheduleSkeleton/components/SidebarSkeleton/SidebarSkeleton.styles.js
  src/components/UI/Skeleton/Pages/ScheduleSkeleton/components/SidebarSkeleton/index.js
  src/components/UI/Skeleton/Pages/ScheduleSkeleton/index.js
  src/components/UI/Skeleton/index.js
  src/pages/ShedulePage/SchedulePage.jsx
Labels: enhancement

#933 932 skeleton spec
  src/components/PageComponents/SpecializationComponents/Interviews/Interviews.styles.js
  src/components/PageComponents/SpecializationComponents/SpecializationCategories/SpecializationCategories.jsx
  src/components/PageComponents/SpecializationComponents/SpecializationLevel/SpecializationLevel.jsx
  src/components/PageComponents/SpecializationComponents/Statistics/HardSkillsChart/HardSkillsChart.jsx
  src/components/PageComponents/SpecializationComponents/Statistics/InteviewChart/InterviewChart.jsx
  src/components/PageComponents/SpecializationComponents/Statistics/LevelChart/LevelChart.jsx
  src/components/PageComponents/SpecializationComponents/Statistics/SkillAssessmentChart/SkillsAssessmentChart.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/CategoriesSkeleton/CategoriesSkeleton.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/CategoriesSkeleton/CategoriesSkeleton.styles.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/CategoriesSkeleton/index.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/HardSkillsChartSkeleton/HardSkillsChartSkeleton.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/HardSkillsChartSkeleton/HardSkillsChartSkeleton.styles.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/HardSkillsChartSkeleton/index.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/InterviewChartSkeleton/InterviewChartSkeleton.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/InterviewChartSkeleton/InterviewChartSkeleton.styles.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/InterviewChartSkeleton/index.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/InterviewsSkeleton/InterviewsSkeleton.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/InterviewsSkeleton/InterviewsSkeleton.styles.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/InterviewsSkeleton/index.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/LevelChartSkeleton/LevelChartSkeleton.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/LevelChartSkeleton/LevelChartSkeleton.styles.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/LevelChartSkeleton/index.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/LevelSkeleton/LevelSkeleton.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/LevelSkeleton/LevelSkeleton.styles.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/LevelSkeleton/index.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/SkillsAssessmentChartSkeleton/SkillsAssessmentChartSkeleton.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/SkillsAssessmentChartSkeleton/SkillsAssessmentChartSkeleton.styles.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/SkillsAssessmentChartSkeleton/index.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/SkillsSkeleton/SkillsSkeleton.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/SkillsSkeleton/SkillsSkeleton.styles.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/SkillsSkeleton/index.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/index.js
  src/components/UI/Skeleton/index.js
  src/components/UI/Specialization/SpecializationSkills/SpecializationSkills.jsx
  src/pages/HomePage/sections/HeroSection/HeroSection.module.scss
  src/pages/SpecializationPage/SpecialisationPage.jsx
Labels: enhancement

#935 934 skeleton profile
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/BaseUserInfoSkeleton/BaseUserInfoSkeleton.jsx
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/BaseUserInfoSkeleton/BaseUserInfoSkeleton.styles.js
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/BaseUserInfoSkeleton/index.js
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/ExperienceSectionSkeleton/ExperienceSectionSkeleton.jsx
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/ExperienceSectionSkeleton/ExperienceSectionSkeleton.styles.js
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/ExperienceSectionSkeleton/index.js
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/RightSectionSkeleton/RightSectionSkeleton.jsx
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/RightSectionSkeleton/RightSectionSkeleton.styles.js
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/RightSectionSkeleton/index.js
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/SkillsSectionSkeleton/SkillsSectionSkeleton.jsx
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/SkillsSectionSkeleton/SkillsSectionSkeleton.styles.js
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/SkillsSectionSkeleton/index.js
  src/components/UI/Skeleton/Pages/personalProfileSkeleton/index.js
  src/components/UI/Skeleton/index.js
  src/pages/ProfilePages/PersonalProfilePage/PersonalProfilePage.jsx
Labels: enhancement

#937 936 skeleton
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserBaseUserInfoSkeleton/UserBaseUserInfoSkeleton.jsx
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserBaseUserInfoSkeleton/UserBaseUserInfoSkeleton.styles.js
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserBaseUserInfoSkeleton/index.js
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserExperienceSectionSkeleton/UserExperienceSectionSkeleton.jsx
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserExperienceSectionSkeleton/UserExperienceSectionSkeleton.styles.js
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserExperienceSectionSkeleton/index.js
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserProfileSkeleton.jsx
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserRightSectionSkeleton/UserRightSectionSkeleton.jsx
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserRightSectionSkeleton/UserRightSectionSkeleton.styles.js
  src/components/UI/Skeleton/Pages/userProfileSkeleton/UserRightSectionSkeleton/index.js
  src/components/UI/Skeleton/Pages/userProfileSkeleton/index.js
  src/components/UI/Skeleton/index.js
  src/pages/ProfilePages/UserProfilePage/UserProfilePage.jsx
Labels: enhancement

#960 Autocomplete turned off
  src/components/ModalsComponents/AuthModals/ConfirmationModal/ConfirmationForm.jsx
Labels: bug

#961 815 bug fix
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepAvatar/StepAvatar.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/StepContacts.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/helpers/addHttps.js
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/helpers/addTelegram.js
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/helpers/index.js
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepLanguage/StepLanguage.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepPersonal/StepPersonal.jsx
  src/components/UI/LoadImages/LoadImages.jsx
  src/components/UI/LoadImages/LoadImages.styles.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepAvatarSkeleton/StepAvatarSkeleton.jsx
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepAvatarSkeleton/StepAvatarSkeleton.styles.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepAvatarSkeleton/index.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepContactsSkeleton/StepContactsSkeleton.jsx
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepContactsSkeleton/StepContactsSkeleton.styles.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepContactsSkeleton/index.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepLanguageSkeleton/StepLanguageSkeleton.jsx
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepLanguageSkeleton/StepLanguageSkeleton.styles.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepLanguageSkeleton/index.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepPersonalSkeleton/StepPersonalSkeleton.jsx
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepPersonalSkeleton/StepPersonalSkeleton.styles.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/StepPersonalSkeleton/index.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/components/BtnSkeleton/BtnSkeleton.jsx
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/components/BtnSkeleton/BtnSkeleton.styles.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/components/BtnSkeleton/index.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/components/index.js
  src/components/UI/Skeleton/Modal/UserInfoModalSkeleton/index.js
  src/components/UI/Skeleton/Modal/index.js
  src/components/UI/Skeleton/Pages/specializationSkeleton/CategoriesSkeleton/CategoriesSkeleton.jsx
  src/components/UI/Skeleton/Pages/specializationSkeleton/CategoriesSkeleton/CategoriesSkeleton.styles.js
  src/components/UI/Skeleton/index.js
  src/redux/user/contacts/contactsApiSlice.js
  src/utils/helpers/helpersForStepContactModal.js
  terraform/deploy_service/task_defenition.tf
Labels: bug, DevBug

#912 972 bug fix
  src/redux/addButton/addButtonSlice.js
  src/redux/chart/chartApiSlice.js
  src/redux/countryList/countryApiSlice.js
  src/redux/feedback/interviewApiSlice.js
  src/redux/interview/interviewApiSlice.js
  src/redux/schedule/scheduleApiSlice.js
  src/redux/services/achievementsApiSlice.js
  src/redux/services/api/apiSlice.js
  src/redux/services/defaultLanguage/defaultLanguageApiSlice.js
  src/redux/services/educationApiSlice.js
  src/redux/services/feedbackProjectModalApiSlice.js
  src/redux/services/languagesApiSlice.js
  src/redux/services/notificationsApiSlice.js
  src/redux/services/skillsApiSlice.js
  src/redux/specialization/specializationApiSlice.js
  src/redux/specialization/specializationList/specializationListApiSlice.js
  src/redux/user/avatar/avatarApiSlice.js
  src/redux/user/contacts/contactsApiSlice.js
  src/redux/user/language/languageApiSlice.js
  src/redux/user/personal/personalApiSlice.js
  src/redux/workExperience/workExperienceApiSlice.js
  src/utils/constants/tagTypes.js
Labels: bug, DevBug

#973 Bugfix/629 my profile languages
  src/components/FormsComponents/Inputs/FormSelect/FormSelect.styles.js
  src/components/FormsComponents/Inputs/SelectLanguage/SelectLanguage.jsx
  src/components/FormsComponents/Inputs/SelectLanguage/SelectLanguage.styles.js
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepLanguage/StepLanguage.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepLanguage/StepLanguage.styles.js
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.styles.js
Labels: bug

#980 #955 added a check for status code 409 and error message in that case
  package-lock.json
  package.json
  src/components/ModalsComponents/AuthModals/RegistrationModal/RegistrationModal.jsx
Labels: bug

#974 fixed spoilers and added ItemFaq component
  .env
  src/pages/HomePage/sections/FAQSection/Faq.module.scss
  src/pages/HomePage/sections/FAQSection/FaqSection.jsx
  src/pages/HomePage/sections/FAQSection/ItemFaq/ItemFaq.jsx
  src/pages/HomePage/sections/FAQSection/ItemFaq/ItemFaq.module.scss
  src/pages/HomePage/sections/FAQSection/ItemFaq/index.js
  src/utils/theme/colors.scss
Labels: bug
