Repository ratifire/devrate-web, pull requests merged in 2025-04, with the labels that each got.

#1297 DW-1292/Localization request tab
  src/components/ModalsComponents/InterviewModals/components/ScheduleInterviewSlotsComponent/components/RenderTimeSlots.jsx
  src/components/PageComponents/InterviewRequest/InterviewRequest.jsx
  src/components/PageComponents/InterviewRequest/RequsestHeader/RequestHeader.jsx
  src/components/PageComponents/InterviewRequest/TimeSlotsGroup/TimeSlotsGroup.jsx
  src/components/PageComponents/InterviewRequest/TimeSlotsGroup/TimeSlotsGroup.styles.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: DevBug

#1296 DW-1282/Education tab, end year localization
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Education/Education.jsx
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: DevBug

#1307 #1286 long name scheduled interview
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Achievement/AchievementItem/AchievementItem.jsx
  src/components/UI/Interview/UserCard/UserCard.styles.js
  src/utils/validationSchemas/AchievementModalSchema.js
Labels: bug

#1310 DW-1303/Interview feedback functionality should not be displayed for candidate
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/components/CandidateFeedback/CandidateFeedback.jsx
  src/utils/locales/uk/index.js
Labels: DevBug

#1346 #1329
  src/components/PageComponents/Menu/Menu.jsx
  vite.config_remote.js
Labels: bug

#1305 add translation to role in SideBarEvent
  src/components/PageComponents/InterviewRequest/Participant/Participant.jsx
  src/components/PageComponents/InterviewsComponents/InterviewInfo/InterviewInfo.jsx
  src/components/PageComponents/InterviewsComponents/InterviewSideBarEvent/SideBarEvent.jsx
  src/utils/helpers/formatRoleLetterCase.js
  src/utils/helpers/index.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: DevBug

#1306 added translation of skills to Statistics
  src/components/PageComponents/SingleScheduledInterview/Statistic/Statistic.jsx
  src/utils/locales/uk/index.js
Labels: DevBug

#1308 Dw 1288/add translation to interview status
  src/components/PageComponents/SingleScheduledInterview/ScheduledMeeting/ScheduledMeeting.jsx
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: DevBug

#1354 1309 feat other skills
  .env
  .gitignore
  src/components/PageComponents/SingleScheduledInterview/InterviewSkills/InterviewSkills.jsx
  src/components/PageComponents/SingleScheduledInterview/InterviewSkills/InterviewSkills.styles.js
  src/components/PageComponents/SingleScheduledInterview/InterviewSkills/components/SkillsParticipant/SkillsParticipant.jsx
  src/components/PageComponents/SingleScheduledInterview/InterviewSkills/components/SkillsParticipant/SkillsParticipant.styles.js
  src/components/PageComponents/SingleScheduledInterview/InterviewSkills/components/SkillsParticipantItem/SkillsParticipantItem.jsx
  src/components/PageComponents/SingleScheduledInterview/InterviewSkills/components/SkillsParticipantItem/SkillsParticipantItem.styles.js
  src/components/PageComponents/SingleScheduledInterview/helpers/matchSkills.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/theme/interview/interviewDark.js
  src/utils/theme/interview/interviewLight.js
Labels: enhancement

#1355 #1316was added link to specific host by id
  src/components/PageComponents/InterviewsComponents/InterviewInfo/InterviewInfo.jsx
  src/components/PageComponents/InterviewsComponents/InterviewInfo/InterviewInfo.styles.js
Labels: Tech. Debt

#1360 1357 checkbox
  src/components/ModalsComponents/InterviewModals/components/TimeSlotInfo/TimeSlotInfo.jsx
  src/components/ModalsComponents/InterviewModals/components/TimeSlotInfo/TimeSlotInfo.styles.js
  src/components/ModalsComponents/InterviewModals/hooks/useScheduleInterviewForm.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: enhancement

#1377 1376 refactor
  src/components/ModalsComponents/AuthModals/RegistrationModal/RegistrationModal.jsx
  src/pages/HomePage/assets/aboutUsMascot/mascotMobile.svg
  src/pages/HomePage/assets/hero/coloredBallsMobil.svg
  src/pages/HomePage/assets/hero/coloredBallsTablet.svg
  src/pages/HomePage/assets/hero/coloredBallsTablet1.svg
  src/pages/HomePage/assets/purpleBallBottomMobile.svg
  src/pages/HomePage/assets/purpleBallBottomTablet.svg
  src/pages/HomePage/sections/AboutUsSection/AboutUsSection.jsx
  src/pages/HomePage/sections/AboutUsSection/AboutUsSection.module.scss
  src/pages/HomePage/sections/Header/Header.module.scss
  src/pages/HomePage/sections/HeroSection/HeroSection.module.scss
  src/pages/HomePage/styles/index.css
  src/utils/constants/regularExpressions.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/validationSchemas/RegistrationSchema.js
Labels: bug

#1405 1400 open graph
  index.html
  public/assets/logo-open-graph.png
Labels: enhancement

#1387 Сторінка інтервью -> запити #1324
  src/pages/InterviewPages/InterviewRequestsPage/InterviewRequestsPage.jsx
Labels: bug

#1380 #1372 | refactor: NotificationModal.jsx
  src/components/ModalsComponents/AuthModals/LoginModal/LoginModal.styles.js
  src/components/ModalsComponents/AuthModals/RegistrationModal/RegistrationModal.styles.js
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/CheckEmail/CheckEmail.styles.js
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/NotificationModal/NotificationModal.jsx
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/NotificationModal/NotificationModal.styles.js
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/ResetPassword/ResetPassword.jsx
  src/components/ModalsComponents/AuthModals/ResetPasswordModal/ResetPassword/ResetPassword.styles.js
  src/components/ModalsComponents/AuthModals/index.js
  src/components/ModalsComponents/ModalContainer.jsx
  src/utils/constants/modalNames.js
  src/utils/locales/uk/index.js
Labels: bug

#1379 1372 bug fix
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepPersonal/StepPersonal.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/BaseUserInfo/BaseUserInfo.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/BaseUserInfo/BaseUserInfo.styles.js
Labels: bug

#1378 #1337 | refactor: locales
  src/utils/locales/uk/index.js
Labels: bug

#1366 Swapped variables completedInterviews and conductedInterviews.
  src/components/PageComponents/ProfileComponents/PersonalProfile/SkillsSection/SkillsSection.jsx
Labels: bug

#1363 1350 sso
  src/assets/icons/AuthLogo/google.svg
  src/assets/icons/AuthLogo/linkedin.svg
  src/components/FormsComponents/Inputs/FormCheckbox/FormCheckbox.jsx
  src/components/ModalsComponents/AuthModals/LoginModal/LoginModal.jsx
  src/components/ModalsComponents/AuthModals/OAuthSection/OAuthSection.jsx
  src/components/ModalsComponents/AuthModals/OAuthSection/OAuthSection.styles.js
  src/components/ModalsComponents/AuthModals/OAuthSection/index.js
  src/components/ModalsComponents/AuthModals/RegistrationModal/RegistrationModal.jsx
  src/components/ModalsComponents/AuthModals/RegistrationModal/RegistrationModal.styles.js
  src/pages/HomePage/HomePage.jsx
  src/redux/api/slices/auth/authApiSlice.js
  src/utils/hoc/index.js
  src/utils/hoc/withAuth.jsx
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/validationSchemas/RegistrationSchema.js
Labels: enhancement

#1365 #1311 blank hard skills
  src/components/PageComponents/InterviewsComponents/InterviewSideBar/SideBar.styles.js
  src/components/PageComponents/InterviewsComponents/InterviewStatistics/InterviewStatistics.jsx
  src/components/UI/Specialization/EmptySkills/EmptySkills.styles.js
  src/components/UI/Specialization/SpecializationSkills/SpecializationSkills.jsx
  src/components/UI/Specialization/SpecializationSkills/SpecializationSkills.styles.js
  src/pages/InterviewPages/PassedInterviewsPage/PassedInterviewsPage.styles.js
  src/pages/InterviewPages/SinglePassedInterviewPage/SingleIPassednterviewPage.styles.js
  src/pages/InterviewPages/SinglePassedInterviewPage/SinglePassedInterviewPage.jsx
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: DevBug
