Repository ratifire/devrate-web, pull requests merged in 2025-03, with the labels that each got.

#1172 Dw 1142/schedule interview modal
  src/components/ModalsComponents/InterviewModals/ScheduleInterviewModal/ScheduleInterviewModal.jsx
  src/components/ModalsComponents/InterviewModals/ScheduleInterviewModal/ScheduleInterviewModal.styles.js
  src/components/ModalsComponents/InterviewModals/components/ScheduleInterviewSlotsComponent/ScheduleInterviewSlots.jsx
  src/components/ModalsComponents/InterviewModals/components/ScheduleInterviewSlotsComponent/ScheduleInterviewSlots.styles.js
  src/components/ModalsComponents/InterviewModals/hooks/useScheduleInterviewForm.js
  src/components/PageComponents/InterviewRequest/Participant/Participant.jsx
  src/components/PageComponents/InterviewRequest/RequsestHeader/RequestHeader.jsx
  src/components/PageComponents/InterviewsComponents/InterviewHeader/InterviewHeader.jsx
  src/redux/interviews/interviewRequestsApiSlice.js
  src/utils/constants/tagTypes.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/validationSchemas/ScheduleInterviewSchema.js
Labels: enhancement

#1187 Fix schedule
  src/assets/icons/cancel-event.svg
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.jsx
  src/components/PageComponents/ScheduleComponents/EventPopup/EventPopup.styles.js
  src/components/PageComponents/ScheduleComponents/Schedule.jsx
  src/redux/schedule/scheduleApiSlice.js
  src/utils/hooks/useDeleteEvent.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: DevBug

#1201 Created more informative error messages.
  src/components/UI/LoadImages/LoadImages.jsx
  src/components/UI/LoadImages/LoadImages.styles.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: bug

#1199 Fixed the text area to match figma
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepPersonal/StepPersonal.jsx
Labels: bug

#1197 Fixed bug that the save button does not work when editing personal in…
  src/utils/validationSchemas/StepPersonalSchema.js
Labels: bug

#1196 Fixed bug after deleting a request, not creating the same duplicate
  src/redux/interviews/interviewRequestsApiSlice.js
Labels: bug

#1206 1192
  .env.local
  src/components/PageComponents/Notification/NotificationsType/InterviewRejected.jsx
  src/utils/helpers/dateHandlers.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  vite.config_remote.js
Labels: bug

#1204 DW-1185/Disable-schedule-btn-if-num-of-Interview-less-than-expected
  src/components/ModalsComponents/InterviewModals/ScheduleInterviewModal/ScheduleInterviewModal.jsx
Labels: bug

#1218 ticket #1217 | Fixed interview request time slots
  .env.local
  src/components/PageComponents/InterviewRequest/Participant/Participant.jsx
  src/components/PageComponents/InterviewRequest/TimeSlot/TimeSlot.jsx
  src/components/PageComponents/InterviewRequest/TimeSlot/TimeSlot.styles.js
  src/components/PageComponents/InterviewRequest/TimeSlotsGroup/TimeSlotsGroup.jsx
  src/components/PageComponents/InterviewRequest/interviewRequestsManageData.js
  src/redux/services/interviewRequestApiSlice.js
  src/utils/locales/en/index.js
  src/utils/theme/interviewRequest/interviewRequestDark.js
  src/utils/theme/interviewRequest/interviewRequestLight.js
Labels: enhancement

#1220 #1209
  src/utils/validationSchemas/ScheduleInterviewSchema.js
Labels: bug

#1221 #1219
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/StepContacts.jsx
  src/utils/helpers/urlHelpers.js
Labels: bug

#1228 fixed bug with error message
  src/components/ModalsComponents/SpecializationModals/ConfirmDeleteSpecializationModal/ConfirmDeleteSpecializationModal.jsx
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: bug

#1237 #1215
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.jsx
Labels: bug

#1248 #1246
  .github/workflows/build.yml
  .github/workflows/build_and_deploy_new_image.yml
  .github/workflows/deploy_service.yml
  .github/workflows/destroy.yml
  .github/workflows/destroy_service.yml
  .github/workflows/down_infrastructure.yml
  .github/workflows/main_init.yml
  .github/workflows/up_infrastructure.yml
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/StepContacts.jsx
  src/components/PageComponents/Chat/ChatForm/ChatForm.jsx
  src/components/PageComponents/Chat/ChatForm/ChatForm.styles.js
  src/components/PageComponents/Notification/NotificationsType/InterviewFeedback.jsx
  src/components/PageComponents/Notification/NotificationsType/InterviewRejected.jsx
  src/components/PageComponents/Notification/NotificationsType/InterviewScheduled.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/RightSection/RightSection.jsx
  src/components/UI/SocialsLinkList/SocialsLinkList.jsx
  src/components/UI/TimeAgo/TimeAgo.jsx
  src/pages/HomePage/sections/Footer/Footer.jsx
  src/redux/services/notificationsApiSlice.js
  src/utils/constants/datesConfig.js
  src/utils/helpers/convertMilliInYears.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/theme/chat/chatDark.js
  src/utils/theme/chat/chatLight.js
  terraform/deploy_service/data.tf
  terraform/deploy_service/deploy.tf
  terraform/deploy_service/dev_old.backend
  terraform/deploy_service/dev_old.tfvars
  terraform/deploy_service/load_balancer_setup.tf
  terraform/deploy_service/output.tf
  terraform/deploy_service/prod.backend
  terraform/deploy_service/prod.tfvars
  terraform/deploy_service/set_domain.tf
  terraform/deploy_service/task_defenition.tf
  terraform/deploy_service/variables.tf
  terraform/infrastructure/dev_old.backend
  terraform/infrastructure/dev_old.tfvars
  terraform/infrastructure/key_pair.tf
  terraform/infrastructure/output.tf
  terraform/infrastructure/prod.backend
  terraform/infrastructure/prod.tfvars
  terraform/infrastructure/repository.tf
  terraform/infrastructure/roles.tf
  terraform/infrastructure/security_group.tf
  terraform/infrastructure/variables.tf
  terraform/output/data.tf
  terraform/output/main.tf
  terraform/output/output.tf
Labels: bug

#1253 fix dateTime, notification
  src/components/UI/TimeAgo/TimeAgo.jsx
Labels: bug

#1256 reworked personal schema
  src/utils/validationSchemas/StepPersonalSchema.js
Labels: bug

#1264 #1260 eyes hiden fix condition
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsItem/SkillsItem.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/Skills.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/styles/index.css
Labels: DevBug

#1278 DW-1276/Leave feedback interview
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/components/CandidateFeedback/CandidateFeedback.jsx
Labels: bug

#1280 Feature/rework step contacts phone input
  package-lock.json
  package.json
  src/components/FormsComponents/Inputs/PhoneInput/PhoneHelperText/PhoneHelperText.jsx
  src/components/FormsComponents/Inputs/PhoneInput/PhoneHelperText/PhoneHelperText.styles.js
  src/components/FormsComponents/Inputs/PhoneInput/PhoneHelperText/index.js
  src/components/FormsComponents/Inputs/PhoneInput/PhoneInput.jsx
  src/components/FormsComponents/Inputs/PhoneInput/PhoneInput.styles.js
  src/components/FormsComponents/Inputs/PhoneInput/index.js
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/StepContacts.jsx
  src/utils/helpers/urlHelpers.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/validationSchemas/StepContactsSchema.js
Labels: enhancement
