Repository ratifire/devrate-web, pull requests merged in 2025-02, with the labels that each got.

#1122 Dw 1097/interview sidebar section
  src/assets/icons/InterviewPageIcons/lime-ellipse.svg
  src/assets/icons/InterviewPageIcons/orange-ellipse.svg
  src/components/PageComponents/InterviewHeader/index.js
  src/components/PageComponents/InterviewsComponents/InterviewHeader/InterviewHeader.jsx
  src/components/PageComponents/InterviewsComponents/InterviewHeader/InterviewHeader.styles.js
  src/components/PageComponents/InterviewsComponents/InterviewHeader/index.js
  src/components/PageComponents/InterviewsComponents/InterviewSideBar/SideBar.jsx
  src/components/PageComponents/InterviewsComponents/InterviewSideBar/SideBar.styles.js
  src/components/PageComponents/InterviewsComponents/InterviewSideBar/index.js
  src/components/PageComponents/InterviewsComponents/InterviewSideBarEvent/SideBarEvent.jsx
  src/components/PageComponents/InterviewsComponents/InterviewSideBarEvent/SideBarEvent.styles.js
  src/components/PageComponents/InterviewsComponents/InterviewSideBarEvent/index.js
  src/components/PageComponents/ScheduleComponents/SidebarEvent/SidebarEvent.jsx
  src/components/PageComponents/ScheduleComponents/SidebarEvent/SidebarEvent.styles.js
  src/components/UI/Skeleton/Pages/InterviewsSkeleton/InterviewsSkeleton.jsx
  src/components/UI/Skeleton/Pages/InterviewsSkeleton/InterviewsSkeleton.styles.js
  src/components/UI/Skeleton/Pages/InterviewsSkeleton/index.js
  src/pages/HomePage/sections/FAQSection/faqData.js
  src/pages/InterviewPages/InterviewRootPage.jsx
  src/pages/InterviewPages/PassedInterviewsPage/PassedInterviewsPage.jsx
  src/pages/InterviewPages/PassedInterviewsPage/PassedInterviewsPage.styles.js
  src/pages/InterviewPages/ScheduledInterviewsPage/ScheduledInterviewsPage.jsx
  src/pages/InterviewPages/ScheduledInterviewsPage/ScheduledInterviewsPage.styles.js
  src/pages/InterviewPages/SinglePassedInterviewPage/SingleIPassednterviewPage.styles.js
  src/pages/InterviewPages/SinglePassedInterviewPage/SinglePassedInterviewPage.jsx
  src/pages/InterviewPages/SingleScheduledInterviewPage/SingleScheduledInterviewPage.jsx
  src/pages/InterviewPages/SingleScheduledInterviewPage/SingleScheduledInterviewPage.styles.js
  src/redux/interviews/passedInterviewsApiSlice.js
  src/redux/interviews/scheduledInterviewsApiSlice.js
  src/router/router.jsx
  src/utils/constants/masteryLvl.js
  src/utils/helpers/formatDateAndTime.js
  src/utils/helpers/index.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: enhancement

#1149 fix: LoadImages.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepAvatar/StepAvatar.jsx
  src/components/UI/LoadImages/LoadImages.jsx
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/validationSchemas/StepAvatarSchema.js
  src/utils/validationSchemas/index.js
Labels: bug, DevBug

#1110 1092
  .env
  .env.local
  .github/workflows/build.yml
  package-lock.json
  package.json
  src/components/ModalsComponents/ModalLayout.styles.js
  src/components/PageComponents/Chat/Chat.jsx
  src/components/PageComponents/Chat/Chat.styles.js
  src/components/PageComponents/Chat/ChatForm/CharFrom.styles.js
  src/components/PageComponents/Chat/ChatForm/ChatForm.jsx
  src/components/PageComponents/Chat/ChatForm/ChatForm.styles.js
  src/components/PageComponents/Chat/ChatForm/ChatMessage/ChatMessage.jsx
  src/components/PageComponents/Chat/ChatForm/ChatMessage/ChatMessage.styles.js
  src/components/PageComponents/Chat/ChatForm/index.js
  src/components/PageComponents/Chat/ChatHistory/ChatHistory.jsx
  src/components/PageComponents/Chat/ChatHistory/ChatHistory.styles.js
  src/components/PageComponents/Chat/ChatHistory/ChatHistoryItem/ChatHistoryItem.jsx
  src/components/PageComponents/Chat/ChatHistory/ChatHistoryItem/ChatHistoryItem.styles.js
  src/components/PageComponents/Chat/ChatHistory/ChatHistoryItem/index.js
  src/components/PageComponents/Chat/ChatHistory/index.js
  src/components/PageComponents/Chat/hooks/index.js
  src/components/PageComponents/Chat/hooks/searchUser.js
  src/components/PageComponents/Chat/hooks/useMoveChat.js
  src/components/PageComponents/Chat/hooks/useResizeChat.js
  src/components/PageComponents/Chat/hooks/useResizeTextarea.js
  src/components/PageComponents/Chat/hooks/useScrollChat.js
  src/components/PageComponents/Menu/Menu.jsx
  src/components/PageComponents/Menu/Menu.styles.js
  src/components/PageComponents/Notification/Notification.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/BaseUserInfo/BaseUserInfo.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/BaseUserInfo/BaseUserInfo.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/Skills.jsx
  src/components/PageComponents/ProfileHeader/InputSearch/ModalSearch/ModalSearch.jsx
  src/components/PageComponents/ProfileHeader/InputSearch/ModalSearch/ModalSearch.styles.js
  src/components/PageComponents/ProfileHeader/ProfileHeader.jsx
  src/components/UI/Skeleton/index.js
  src/components/UI/UserAvatar/UserAvatar.jsx
  src/components/UI/UserAvatar/UserAvatar.styles.js
  src/pages/RootPage/RootPage.jsx
  src/redux/chat/chatSlice.js
  src/redux/services/chatApiSlice.js
  src/redux/services/notificationsApiSlice.js
  src/redux/store/store.js
  src/utils/constants/tagTypes.js
  src/utils/constants/testMessages.js
  src/utils/helpers/dateHandlers.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/theme/chat/chatDark.js
  src/utils/theme/chat/chatLight.js
  src/utils/theme/chat/index.js
  src/utils/theme/theme.js
  vite.config_remote.js
Labels: enhancement

#1157 fix: ModalLayout.styles.js
  src/components/ModalsComponents/ModalLayout.styles.js
Labels: DevBug

#1158 Feat modal feedback
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/FeedbackInterviewModal.jsx
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/hooks/useFeedbackForm.js
  src/components/PageComponents/ProfileHeader/ProfileHeader.jsx
  src/components/PageComponents/SingleScheduledInterview/ScheduledMeeting/ScheduledMeeting.jsx
  src/redux/feedback/interviewApiSlice.js
Labels: DevBug

#1160 Empty spec
  src/assets/pictures/emptySkillsAndLayersPictures/emptyHardSkillsLayerDark.svg
  src/assets/pictures/emptySkillsAndLayersPictures/emptyHardSkillsLayerLight.svg
  src/assets/pictures/emptySkillsAndLayersPictures/skillsMascot/hardSkillsMascotDark.svg
  src/assets/pictures/emptySkillsAndLayersPictures/skillsMascot/hardSkillsMascotLight.svg
  src/assets/pictures/emptySkillsAndLayersPictures/skillsMascot/softSkillsMascotDark.svg
  src/assets/pictures/emptySkillsAndLayersPictures/skillsMascot/softSkillsMascotLight.svg
  src/components/PageComponents/SpecializationComponents/SpecializationCategories/SpecializationCategories.styles.js
  src/components/PageComponents/SpecializationComponents/SpecializationLevel/SpecializationLevel.jsx
  src/components/PageComponents/SpecializationComponents/SpecializationLevel/SpecializationLevel.styles.js
  src/components/PageComponents/SpecializationComponents/Statistics/HardSkillsChart/HardSkillsChart.jsx
  src/components/PageComponents/SpecializationComponents/Statistics/HardSkillsChart/HardSkillsChart.styles.js
  src/components/PageComponents/SpecializationComponents/Statistics/InteviewChart/InterviewChart.jsx
  src/components/PageComponents/SpecializationComponents/Statistics/InteviewChart/InterviewChart.styles.js
  src/components/PageComponents/SpecializationComponents/Statistics/LevelChart/LevelChart.styles.js
  src/components/PageComponents/SpecializationComponents/Statistics/SkillAssessmentChart/SkillsAssessmentChart.jsx
  src/components/PageComponents/SpecializationComponents/Statistics/SkillAssessmentChart/SkillsAssessmentChart.styles.js
  src/components/PageComponents/SpecializationComponents/Statistics/utils/helpers/getCurrentAndLastMonths.js
  src/components/PageComponents/SpecializationComponents/Statistics/utils/index.js
  src/components/UI/Specialization/EmptySkills/EmptySkills.jsx
  src/components/UI/Specialization/EmptySkills/EmptySkills.styles.js
  src/components/UI/Specialization/EmptySkills/index.js
  src/components/UI/Specialization/SpecializationSkills/SpecializationSkills.jsx
  src/components/UI/Specialization/SpecializationSkills/SpecializationSkills.styles.js
  src/pages/SpecializationPage/SpecialisationPage.styles.js
  src/redux/chart/chartApiSlice.js
  src/utils/locales/en/index.js
Labels: enhancement

#1161 #1131 request interview page
  src/components/FormsComponents/Buttons/ButtonDef/ButtonDef.jsx
  src/components/PageComponents/InterviewRequest/InterviewRequest.jsx
  src/components/PageComponents/InterviewRequest/InterviewRequest.styles.js
  src/components/PageComponents/InterviewRequest/Participant/Participant.jsx
  src/components/PageComponents/InterviewRequest/Participant/Participant.styles.js
  src/components/PageComponents/InterviewRequest/Participant/index.js
  src/components/PageComponents/InterviewRequest/RequsestHeader/RequestHeader.jsx
  src/components/PageComponents/InterviewRequest/RequsestHeader/RequestHeader.styles.js
  src/components/PageComponents/InterviewRequest/RequsestHeader/index.js
  src/components/PageComponents/InterviewRequest/TimeSlot/TimeSlot.jsx
  src/components/PageComponents/InterviewRequest/TimeSlot/TimeSlot.styles.js
  src/components/PageComponents/InterviewRequest/TimeSlot/index.js
  src/components/PageComponents/InterviewRequest/TimeSlotsGroup/TimeSlotsGroup.jsx
  src/components/PageComponents/InterviewRequest/TimeSlotsGroup/TimeSlotsGroup.styles.js
  src/components/PageComponents/InterviewRequest/TimeSlotsGroup/index.js
  src/components/PageComponents/InterviewRequest/index.js
  src/components/PageComponents/InterviewRequest/interviewRequestsManageData.js
  src/components/PageComponents/InterviewRequest/interviewRequestsManageDataOld.js
  src/components/PageComponents/InterviewRequest/interviewRequestsManageDataV2.js
  src/components/UI/Skeleton/Pages/InterviewRequestSkeleton/InterviewRequestSkeleton.jsx
  src/components/UI/Skeleton/Pages/InterviewRequestSkeleton/InterviewRequestSkeleton.styles.js
  src/components/UI/Skeleton/Pages/InterviewRequestSkeleton/index.js
  src/components/UI/Skeleton/index.js
  src/pages/InterviewPages/InterviewRequestsPage/InterviewRequestsPage.jsx
  src/pages/InterviewPages/InterviewRequestsPage/InterviewRequestsPage.styles.js
  src/redux/services/interviewRequestApiSlice.js
  src/utils/constants/tagTypes.js
  src/utils/locales/en/index.js
  src/utils/theme/interviewRequest/index.js
  src/utils/theme/interviewRequest/interviewRequestDark.js
  src/utils/theme/interviewRequest/interviewRequestLight.js
  src/utils/theme/theme.js
  vite.config_remote.js
Labels: enhancement

#1165 Fix submit feedback
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/components/CandidateFeedback/CandidateFeedback.jsx
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/components/InterviewerFeedback/InterviewerFeedback.jsx
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/components/InterviewerInfo/InterviewerInfo.jsx
  src/components/ModalsComponents/FeedbackModal/FeedbackInterviewModal/hooks/useFeedbackForm.js
  src/components/PageComponents/SingleScheduledInterview/ScheduledMeeting/ScheduledMeeting.jsx
  src/components/PageComponents/SingleScheduledInterview/ScheduledMeeting/constants/leftBtnStatus.js
  src/components/PageComponents/SingleScheduledInterview/ScheduledMeeting/constants/rigthBtnStatus.js
  src/redux/feedback/interviewApiSlice.js
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
Labels: DevBug

#1170 Empt pages
  src/assets/pictures/emptyInterviewTabsPictures/noSpecializations/passed.svg
  src/assets/pictures/emptyInterviewTabsPictures/noSpecializations/reqest.svg
  src/assets/pictures/emptyInterviewTabsPictures/noSpecializations/scheduled.svg
  src/assets/pictures/emptyInterviewTabsPictures/passedInterview/passedDark.svg
  src/assets/pictures/emptyInterviewTabsPictures/passedInterview/passedLight.svg
  src/assets/pictures/emptyInterviewTabsPictures/requestInterview/requestDark.svg
  src/assets/pictures/emptyInterviewTabsPictures/requestInterview/requestLight.svg
  src/assets/pictures/emptyInterviewTabsPictures/scheduledInterview/scheduledDark.svg
  src/assets/pictures/emptyInterviewTabsPictures/scheduledInterview/scheduledLight.svg
  src/components/ModalsComponents/SpecializationModals/ConfirmDeleteSpecializationModal/ConfirmDeleteSpecializationModal.jsx
  src/components/ModalsComponents/SpecializationModals/SpecializationModal/SpecializationModal.jsx
  src/components/PageComponents/InterviewRequest/InterviewRequest.jsx
  src/components/PageComponents/SpecializationComponents/Statistics/LevelChart/LevelChart.jsx
  src/pages/InterviewPages/EmptyInterviewTab/EmptyInterviewTab.jsx
  src/pages/InterviewPages/EmptyInterviewTab/EmptyInterviewTab.styles.js
  src/pages/InterviewPages/EmptyInterviewTab/index.js
  src/pages/InterviewPages/PassedInterviewsPage/EmptyPassedInterviewsPage.jsx
  src/pages/InterviewPages/PassedInterviewsPage/EmptyPassedInterviewsPage.styles.js
  src/pages/InterviewPages/PassedInterviewsPage/PassedInterviewsPage.jsx
  src/pages/InterviewPages/ScheduledInterviewsPage/ScheduledInterviewsPage.jsx
  src/utils/constants/emptyTabsPictures.js
  src/utils/locales/en/index.js
Labels: enhancement

#1169 fix: cache
  src/redux/auth/authApiSlice.js
Labels: DevBug
