Repository ratifire/devrate-web, pull requests merged in 2025-08, with the labels that each got.

#1522 #1500 | fix: Long first name and last name in EventPopup.jsx
  src/components/PageComponents/ScheduleComponents/Calendar/EventPopup/EventPopup.jsx
  src/components/PageComponents/ScheduleComponents/Calendar/EventPopup/EventPopup.styles.js
Labels: bug

#1554 Changed the limit to text in the post interview feedback modal.
  src/utils/validationSchemas/FeedbackModalSchema.js
Labels: DevBug

#1538 #1483 video on passed interview page
  package-lock.json
  package.json
  src/components/PageComponents/InterviewsComponents/InterviewInfo/InterviewInfo.jsx
  src/components/PageComponents/InterviewsComponents/InterviewPreviewVideo/InterviewPreviewVideo.jsx
  src/pages/InterviewPages/SinglePassedInterviewPage/SingleIPassednterviewPage.styles.js
  src/pages/InterviewPages/SinglePassedInterviewPage/SinglePassedInterviewPage.jsx
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/theme/interview/interviewDark.js
  src/utils/theme/interview/interviewLight.js
Labels: enhancement
