Repository ratifire/devrate-web, pull requests merged in 2025-01, with the labels that each got.

#1054 update: HUSKY.md
  docs/husky/HUSKY.md
  docs/husky/screenshots/eslint-ignore.png
Labels: documentation

#1066 fix: EmailValidationSchema.js
  src/utils/valadationSchemas/EmailValidationSchema.js
Labels: bug

#1079 refactor: masteryLvl.js
  package-lock.json
  package.json
  src/utils/constants/masteryLvl.js
Labels: Tech. Debt

#1078 #1055
  package-lock.json
  public/assets/favicon.ico
  src/components/ModalsComponents/ProfileModals/EducationModal/EducationModal.jsx
  src/components/ModalsComponents/ProfileModals/EducationModal/EducationModal.styles.js
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/ModalUserInfo.styles.js
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepAvatar/StepAvatar.styles.js
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/StepContacts.jsx
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepContacts/StepContacts.styles.js
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/StepPersonal/StepPersonal.styles.js
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.jsx
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.styles.js
  src/components/PageComponents/FaqComponents/Blog/Blog.jsx
  src/components/PageComponents/FaqComponents/Blog/Blog.styles.js
  src/components/PageComponents/FaqComponents/Faq/Faq.jsx
  src/components/PageComponents/FaqComponents/Faq/Faq.styles.js
  src/components/PageComponents/Menu/Menu.jsx
  src/components/PageComponents/Menu/Menu.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/BaseUserInfo/BaseUserInfo.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/BaseUserInfo/BaseUserInfo.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Achievement/Achievement.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Achievement/Achievement.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Achievement/AchievementItem/AchievementItem.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Achievement/AchievementItem/AchievementItem.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Achievement/Achievment.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/ExperienceSection.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/Skills.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsList/SkillsList.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/Skills/SkillsList/SkillsList.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/WorkExperience/WorkExperienceItem/WorkExperienceItem.jsx
  src/components/PageComponents/ProfileComponents/PersonalProfile/ExperienceSection/WorkExperience/WorkExperienceItem/WorkExperienceItem.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/RightSection/RightSection.styles.js
  src/components/PageComponents/ProfileComponents/PersonalProfile/SkillsSection/SkillsSection.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/BaseUserInfo/BaseUserInfo.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/ExperienceSection.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/Skills.jsx
  src/components/PageComponents/ProfileComponents/UserProfile/ExperienceSection/Skills/Skills.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/RightSection/RightSection.styles.js
  src/components/PageComponents/ProfileComponents/UserProfile/SkillsSection/SkillsSection.styles.js
  src/components/PageComponents/ProfileComponents/sharedComponents/EmptyExperienceTab/EmptyExperienceTab.styles.js
  src/components/PageComponents/ProfileHeader/ProfileHeader.styles.js
  src/components/UI/LoadImages/LoadImages.styles.js
  src/components/UI/StarMainSpecialization/StarMainSpecialization.jsx
  src/components/UI/StarMainSpecialization/StarMainSpecialization.styles.js
  src/components/UI/StarMainSpecialization/index.js
  src/components/UI/UserAvatar/UserAvatar.styles.js
  src/pages/FaqPage/FaqPage.styles.js
  src/pages/ProfilePages/PersonalProfilePage/PersonalProfilePage.styles.js
  src/pages/ProfilePages/UserProfilePage/UserProfilePage.styles.js
Labels: Tech. Debt

#1105 Dw 1096/interview page prep
  src/assets/icons/InterviewPageIcons/green-ellipse.svg
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/ScheduleInterviewModal.jsx
  src/components/PageComponents/InterviewHeader/InterviewHeader.jsx
  src/components/PageComponents/InterviewHeader/InterviewHeader.styles.js
  src/components/PageComponents/InterviewHeader/index.js
  src/pages/InterviewPages/InterviewRequestsPage/InterviewRequestsPage.jsx
  src/pages/InterviewPages/InterviewRequestsPage/index.js
  src/pages/InterviewPages/InterviewRootPage.jsx
  src/pages/InterviewPages/PassedInterviewsPage/PassedInterviewsPage.jsx
  src/pages/InterviewPages/PassedInterviewsPage/index.js
  src/pages/InterviewPages/ScheduledInterviewsPage/ScheduledInterviewsPage.jsx
  src/pages/InterviewPages/ScheduledInterviewsPage/index.js
  src/pages/InterviewPages/SinglePassedInterviewPage/SinglePassedInterviewPage.jsx
  src/pages/InterviewPages/SinglePassedInterviewPage/index.js
  src/pages/InterviewPages/SingleRequestInterviewPage/SingleRequestInterviewPage.jsx
  src/pages/InterviewPages/SingleRequestInterviewPage/index.js
  src/pages/InterviewPages/SingleScheduledInterviewPage/SingleScheduledInterviewPage.jsx
  src/pages/InterviewPages/SingleScheduledInterviewPage/index.js
  src/pages/InterviewPages/index.js
  src/router/guards/UserProfileGuard.jsx
  src/router/links.js
  src/router/router.jsx
  src/utils/locales/en/index.js
  src/utils/locales/uk/index.js
  src/utils/theme/interview/index.js
  src/utils/theme/interview/interviewDark.js
  src/utils/theme/interview/interviewLight.js
  src/utils/theme/theme.js
Labels: enhancement

#1104 changed names of steps and logic of StepLabel renders
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/ModalUserInfo.jsx
  src/utils/locales/en/index.js
Labels: Tech. Debt

#1103 #1072 group date handling
  src/components/ModalsComponents/ProfileModals/ModalUserInfo/ModalUserInfo.jsx
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceEditModal.jsx
  src/components/ModalsComponents/ProfileModals/WorkExperienceModal/WorkExperienceModal.jsx
  src/components/ModalsComponents/SpecializationModals/ScheduleInterviewModal/ScheduleInterviewModal.jsx
  src/components/PageComponents/Notification/NotificationsType/InterviewScheduled.jsx
  src/utils/helpers/checkTimeDifference.js
  src/utils/helpers/dateHandlers.js
  src/utils/helpers/formatToLocalDate.js
  src/utils/helpers/generateYearsArray.js
  src/utils/helpers/getUserUTC.js
  src/utils/helpers/getWeekDates.js
  src/utils/helpers/index.js
  src/utils/hooks/schedule/useCheckTimeDifference.js
Labels: Tech. Debt
